# Generated by Django 5.2.17 on 2026-09-13 11:18

import django.db.models.deletion
import django.utils.timezone
import modelcluster.fields
import modelsearch.index
import taggit.managers
import wagtail.contrib.routable_page.models
import wagtail.fields
import wagtail.images.models
import wagtail.models.media
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("wagtailcore", "0098_apitoken"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.WAGTAIL_PAGE_MODEL,
                    ),
                ),
                (
                    "intro",
                    wagtail.fields.RichTextField(blank=True, verbose_name="توضیح"),
                ),
                (
                    "articles_per_page",
                    models.PositiveSmallIntegerField(
                        default=12, verbose_name="تعداد مقاله در هر صفحه"
                    ),
                ),
            ],
            options={
                "verbose_name": "فهرست مقالات",
                "verbose_name_plural": "فهرست مقالات",
            },
            bases=(
                wagtail.contrib.routable_page.models.RoutablePageMixin,
                "wagtailcore.page",
            ),
        ),
        migrations.CreateModel(
            name="CustomImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "file",
                    wagtail.images.models.WagtailImageField(
                        height_field="height",
                        upload_to=wagtail.images.models.get_upload_to,
                        verbose_name="file",
                        width_field="width",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="description",
                    ),
                ),
                ("width", models.IntegerField(editable=False, verbose_name="width")),
                ("height", models.IntegerField(editable=False, verbose_name="height")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("focal_point_x", models.PositiveIntegerField(blank=True, null=True)),
                ("focal_point_y", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "focal_point_width",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "focal_point_height",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("file_size", models.PositiveIntegerField(editable=False, null=True)),
                (
                    "file_hash",
                    models.CharField(
                        blank=True, db_index=True, editable=False, max_length=40
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        default=wagtail.models.media.get_root_collection_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailcore.collection",
                        verbose_name="collection",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text=None,
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="tags",
                    ),
                ),
                (
                    "uploaded_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="uploaded by user",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                wagtail.images.models.ImageFileMixin,
                modelsearch.index.Indexed,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="نام"),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        help_text="در نشانی صفحه استفاده می\u200cشود: /category/<اسلاگ>/",
                        max_length=120,
                        unique=True,
                        verbose_name="اسلاگ",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="در صفحه\u200cی دسته\u200cبندی نمایش داده می\u200cشود.",
                        max_length=500,
                        verbose_name="توضیح",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="blog.customimage",
                        verbose_name="تصویر",
                    ),
                ),
            ],
            options={
                "verbose_name": "دسته\u200cبندی",
                "verbose_name_plural": "دسته\u200cبندی\u200cها",
                "ordering": ["name"],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name="BlogSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_title",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="نام بلاگ"
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="شعار / زیرعنوان"
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        max_length=300,
                        verbose_name="توضیح متای پیش\u200cفرض",
                    ),
                ),
                (
                    "footer_text",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="متن پاورقی"
                    ),
                ),
                (
                    "main_site_url",
                    models.URLField(
                        blank=True,
                        help_text="لینک بازگشت از بلاگ به سایت اصلی پروژه.",
                        verbose_name="نشانی سایت اصلی",
                    ),
                ),
                ("linkedin", models.URLField(blank=True, verbose_name="لینکدین")),
                (
                    "x_profile",
                    models.URLField(blank=True, verbose_name="ایکس (توییتر)"),
                ),
                ("telegram", models.URLField(blank=True, verbose_name="تلگرام")),
                ("instagram", models.URLField(blank=True, verbose_name="اینستاگرام")),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
                (
                    "default_social_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="blog.customimage",
                        verbose_name="تصویر پیش\u200cفرض اشتراک\u200cگذاری",
                    ),
                ),
                (
                    "favicon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="blog.customimage",
                        verbose_name="فاوآیکون",
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="blog.customimage",
                        verbose_name="لوگو",
                    ),
                ),
            ],
            options={
                "verbose_name": "تنظیمات بلاگ",
            },
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="نام و نام خانوادگی"),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        help_text="در نشانی صفحه استفاده می\u200cشود: /author/<اسلاگ>/",
                        max_length=170,
                        unique=True,
                        verbose_name="اسلاگ",
                    ),
                ),
                (
                    "job_title",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="عنوان شغلی"
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, max_length=1000, verbose_name="معرفی کوتاه"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="ایمیل"),
                ),
                ("website", models.URLField(blank=True, verbose_name="وب\u200cسایت")),
                ("linkedin", models.URLField(blank=True, verbose_name="لینکدین")),
                (
                    "x_profile",
                    models.URLField(blank=True, verbose_name="ایکس (توییتر)"),
                ),
                ("telegram", models.URLField(blank=True, verbose_name="تلگرام")),
                ("instagram", models.URLField(blank=True, verbose_name="اینستاگرام")),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="اختیاری: اتصال این نویسنده به یک کاربر پنل مدیریت.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="author_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر پنل",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="blog.customimage",
                        verbose_name="تصویر",
                    ),
                ),
            ],
            options={
                "verbose_name": "نویسنده",
                "verbose_name_plural": "نویسندگان",
                "ordering": ["name"],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name="ArticlePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.WAGTAIL_PAGE_MODEL,
                    ),
                ),
                (
                    "intro",
                    models.TextField(
                        blank=True,
                        help_text="در فهرست مقالات و توضیحات متای صفحه استفاده می\u200cشود.",
                        max_length=300,
                        verbose_name="چکیده",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("paragraph", 0),
                            ("heading", 3),
                            ("image", 6),
                            ("quote", 9),
                            ("callout", 13),
                            ("code", 16),
                            ("embed", 17),
                            ("html", 18),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h2",
                                        "h3",
                                        "h4",
                                        "bold",
                                        "italic",
                                        "link",
                                        "ol",
                                        "ul",
                                        "hr",
                                        "blockquote",
                                        "code",
                                        "superscript",
                                        "subscript",
                                        "strikethrough",
                                    ],
                                    "label": "متن",
                                    "template": "blog/blocks/paragraph_block.html",
                                },
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "متن سرتیتر", "required": True},
                            ),
                            2: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("h2", "سرتیتر ۲"),
                                        ("h3", "سرتیتر ۳"),
                                        ("h4", "سرتیتر ۴"),
                                    ],
                                    "label": "سطح",
                                },
                            ),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 1), ("level", 2)]],
                                {},
                            ),
                            4: (
                                "wagtail.images.blocks.ImageBlock",
                                [],
                                {"label": "تصویر"},
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "زیرنویس", "required": False},
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 4), ("caption", 5)]],
                                {},
                            ),
                            7: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"label": "متن نقل\u200cقول", "required": True},
                            ),
                            8: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "گوینده / منبع", "required": False},
                            ),
                            9: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 7), ("attribution", 8)]],
                                {},
                            ),
                            10: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("note", "نکته"),
                                        ("tip", "پیشنهاد"),
                                        ("warning", "هشدار"),
                                    ],
                                    "label": "نوع",
                                },
                            ),
                            11: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "عنوان", "required": False},
                            ),
                            12: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link", "ol", "ul"],
                                    "label": "متن",
                                },
                            ),
                            13: (
                                "wagtail.blocks.StructBlock",
                                [[("style", 10), ("title", 11), ("text", 12)]],
                                {},
                            ),
                            14: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("plain", "متن ساده"),
                                        ("python", "Python"),
                                        ("javascript", "JavaScript"),
                                        ("html", "HTML"),
                                        ("css", "CSS"),
                                        ("bash", "Bash"),
                                        ("sql", "SQL"),
                                        ("json", "JSON"),
                                        ("yaml", "YAML"),
                                    ],
                                    "label": "زبان",
                                },
                            ),
                            15: ("wagtail.blocks.TextBlock", (), {"label": "کد"}),
                            16: (
                                "wagtail.blocks.StructBlock",
                                [[("language", 14), ("code", 15)]],
                                {},
                            ),
                            17: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {
                                    "help_text": "نشانی ویدیو (آپارات، یوتیوب و ...) را بگذارید.",
                                    "icon": "media",
                                    "label": "ویدیو / امبد",
                                    "template": "blog/blocks/embed_block.html",
                                },
                            ),
                            18: (
                                "wagtail.blocks.RawHTMLBlock",
                                (),
                                {
                                    "help_text": "فقط برای مواقع لازم؛ محتوای این بلوک بدون فیلتر نمایش داده می\u200cشود.",
                                    "icon": "code",
                                    "label": "کد HTML (پیشرفته)",
                                },
                            ),
                        },
                        verbose_name="بدنه",
                    ),
                ),
                (
                    "publish_date",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="ترتیب نمایش مقالات بر اساس این تاریخ است.",
                        verbose_name="تاریخ انتشار",
                    ),
                ),
                (
                    "featured",
                    models.BooleanField(
                        default=False,
                        help_text="در بالای فهرست مقالات برجسته می\u200cشود.",
                        verbose_name="مقاله\u200cی ویژه",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="blog.author",
                        verbose_name="نویسنده",
                    ),
                ),
                (
                    "categories",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True,
                        related_name="articles",
                        to="blog.category",
                        verbose_name="دسته\u200cبندی\u200cها",
                    ),
                ),
                (
                    "cover_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="blog.customimage",
                        verbose_name="تصویر شاخص",
                    ),
                ),
            ],
            options={
                "verbose_name": "مقاله",
                "verbose_name_plural": "مقالات",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="CustomRendition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filter_spec", models.CharField(db_index=True, max_length=255)),
                (
                    "file",
                    wagtail.images.models.WagtailImageField(
                        height_field="height",
                        storage=wagtail.images.models.get_rendition_storage,
                        upload_to=wagtail.images.models.get_rendition_upload_to,
                        width_field="width",
                    ),
                ),
                ("width", models.IntegerField(editable=False)),
                ("height", models.IntegerField(editable=False)),
                (
                    "focal_point_key",
                    models.CharField(
                        blank=True, default="", editable=False, max_length=16
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="renditions",
                        to="blog.customimage",
                    ),
                ),
            ],
            options={
                "unique_together": {("image", "filter_spec", "focal_point_key")},
            },
            bases=(wagtail.images.models.ImageFileMixin, models.Model),
        ),
    ]
